import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNavbar from "@/components/Navbar/TopNavbar";
import BottomNavbar from "@/components/Navbar/BottomNavbar";
import Newsletter from "@/components/Footer/NewsLetter";
import FooterLinks from "@/components/Footer/FooterLinks";
import MobileTopbar from "@/components/Navbar/mobile/MobileTopbar";
import MobileBottombar from "@/components/Navbar/MobileBottombar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <div className="hidden xl:block">
          <TopNavbar />
          <BottomNavbar />
        </div>
        <div className="xl:hidden ">
          <MobileTopbar />
          <MobileBottombar />
        </div>

        {children}
        <span className="block border-t-1 border-[var(--lightGray6)] w-full my-8" />
        <Newsletter />
        <span className="block border-t-1 border-[var(--lightGray6)] w-full my-8" />
        <FooterLinks />
      </body>
    </html>
  );
}
